### ISSUE TITLE
The Vib Ribbon Minus does not start after adding ru_RU and language strings in languages.json flie

### ISSUE THREAD

**Issue by SuperWillow** [PlayNowKnux/VibRibbonMinusRelease#5]
When I open Vib Ribbon Minus, gives an error message: Traceback (most recent call last):
  File "main.py", line 196, in <module>
  File "main.py", line 187, in load_json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 7 column 3 (char 136)
![Снимок экрана 2024-04-05 225540](https://github.com/PlayNowKnux/VibRibbonMinusRelease/assets/87235362/6013b602-4f7d-4760-b569-791145aa4cf1)
Please fix this error, otherwise the game should launch correctly.

**Comment by PlayNowKnux** [comment]
This looks like an issue with the JSON file itself. Check to make sure there is a comma at the end of line 7 in your locale file.

**Comment by PlayNowKnux** [comment]
You can send over the JSON file and I can take a look at it if you want.
Edit: Sorry for the long response time

**Comment by SuperWillow** [comment]
> This looks like an issue with the JSON file itself. Check to make sure there is a comma at the end of line 7 in your locale file.

The comma is already at the end of line 7, but I don’t see any point in fixing it. If you compare this line with the English translation, then the difference is the same.
![Снимок экрана 2024-12-29 151411](https://github.com/user-attachments/assets/da584f00-8e82-4118-ba78-c82782959ba8)
![Снимок экрана 2024-12-29 152415](https://github.com/user-attachments/assets/68250660-4c95-44a5-9838-ee8a01f79ff7)
Here is the code for this line from my Russian translation:
`"pause_resume": "Продолжить",`
Also, you should look at my JSON file with my translation to see the errors in it. If anything, I'll throw it now.

**Comment by SuperWillow** [comment]
> You can send over the JSON file and I can take a look at it if you want. Edit: Sorry for the long response time

Here is my JSON file with Russian translation, which I have been doing since July 2024:
[ru_RU.json](https://github.com/user-attachments/files/18268885/ru_RU.json)
And while I'm correcting my translation, you can take a look at it for now.

**Comment by SuperWillow** [comment]
> > This looks like an issue with the JSON file itself. Check to make sure there is a comma at the end of line 7 in your locale file.
> 
> The comma is already at the end of line 7, but I don’t see any point in fixing it. If you compare this line with the English translation, then the difference is the same. ![Снимок экрана 2024-12-29 151411](https://private-user-images.githubusercontent.com/87235362/399146370-da584f00-8e82-4118-ba78-c82782959ba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0ODk2NzMsIm5iZiI6MTczNTQ4OTM3MywicGF0aCI6Ii84NzIzNTM2Mi8zOTkxNDYzNzAtZGE1ODRmMDAtOGU4Mi00MTE4LWJhNzgtYzgyNzgyOTU5YmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDE2MjI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3M2QwN2M5Mjk4N2IxMGUzNDkxZDJmY2YxNDgzZTkxNTM4ZGJiMzg1N2ZiNGQ0N2RlYWQ0YmYyNzI5ODhkZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xtXthvog2lI59N03Ci5OboCcG4Jr8QjJKtNoCXIY6rs) ![Снимок экрана 2024-12-29 152415](https://private-user-images.githubusercontent.com/87235362/399146507-68250660-4c95-44a5-9838-ee8a01f79ff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0ODk2NzMsIm5iZiI6MTczNTQ4OTM3MywicGF0aCI6Ii84NzIzNTM2Mi8zOTkxNDY1MDctNjgyNTA2NjAtNGM5NS00NGE1LTk4MzgtZWU4YTAxZjc5ZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDE2MjI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YWY5MTI0M2RlNGFjMzUxZGEwYWUwZjFiNWNlMzA3OWVlZjZiZWMwNmE2ZWM3MzQ2MmYyMjk2ZTRiNmJjNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6j6ht5_WQlRGdeOEz2Wn6o4Ehan9Sh2trFLuo-KPw7Y) Here is the code for this line from my Russian translation: `"pause_resume": "Продолжить",` Also, you should look at my JSON file with my translation to see the errors in it. If anything, I'll throw it now.

No, it turns out that this problem was caused by the fact that it is not the JSON file that is the issue, but the localization file itself. So, you just need to put a comma in the languages.json file and that's it. Now, the game works.
